### ISSUE TITLE
All the image links for the Staking with BNB tutorial are broken

### ISSUE THREAD

**Issue by g-gundam** [bnb-chain/bnb-chain.github.io#240]
Every image in [docs/staking-with-ext-wallet.md](https://github.com/bnb-chain/bnb-chain.github.io/blob/master/docs/staking-with-ext-wallet.md) is broken.

The public URL for the page is:
https://docs.bnbchain.org/docs/staking-with-ext-wallet

**Comment by deepcrazy** [comment]
Thanks for reporting. We'll check with the team internally and update accordingly.
