### ISSUE TITLE
Duplicate or Spam or Scam or Copyright Infringment or Look alike website?

### ISSUE THREAD

**Issue by coder0107git** [bnb-chain/bnb-chain.github.io#270]
It seems that [wwww.bnb-chainexchaing.online](https://wwww.bnb-chainexchaing.online/) is a duplicate of [www.bnbchain.org](https://www.bnbchain.org/). Looking at the copyright at the bottom of the page even says `bnbchain.org`. I'm reporting this here because I don't know where else to report it. I found this duplicate website when I was looking at [this](https://github.com/Joe12387/detectIncognito/issues/21) issue there was a recent post with that link. A message similar to the one I saw posted by the same person is still intact [here](https://github.com/johnrjj/0xQL/pull/2#issuecomment-1906741640).

**Comment by coder0107git** [comment]
There's also another spam message [here](https://github.com/songbingyu/earthshaker/issues/1#issuecomment-1906798690).

**Comment by CocoStarZ** [comment]
[wwww.bnb-chainexchaing.online](https://wwww.bnb-chainexchaing.online/) is the spam website, pls stay away with it. Also you can report the issue on BNBChain discord https://discord.com/channels/789402563035660308/972414416895238144

**Comment by coder0107git** [comment]
Ok, will do.

**Comment by coder0107git** [comment]
It seems that the original url has gone down. I found another bnb-chain spam/scam comment [here](https://github.com/johnrjj/0xQL/pull/2#issuecomment-1870718677) but that website also seems to be dead.

**Comment by coder0107git** [comment]
I also found [this](https://bnbreward-com.web.app/) which is very suspicious. I also unearthed [this](https://medium.com/@stayhealth44/top-7-verified-source-to-get-free-bnb-online-in-2024-7ca244ada053) article that seems to be full of scam links. I guess Google can unearth some very interesting (scammy) [things](https://www.google.com/search?q=bnbrewards.online&safe=active&ssui=on) sometimes.

**Comment by forrestdbrown** [comment]
Does anyone know how long this recovery tool will be available?  Is it safe to wait the 7 days to see how the transfer went or does it end services starting 2025?
