### ISSUE TITLE
Image missing on https://docs.bnbchain.org/docs/verify-proxy/

### ISSUE THREAD

**Issue by k00mu** [bnb-chain/bnb-chain.github.io#288]

**Comment by huihzhao** [comment]
Where did you find the verify-proxy page?

**Comment by HusseinHaji11** [comment]
![Uploading Screenshot_20240706_051230_Telegram.jpg…]()

**Comment by HusseinHaji11** [comment]
I need help me

**Comment by Sqahtni140** [comment]
> انا بحاجة لمساعدتي

**Comment by Sqahtni140** [comment]
https://github.com/bnb-chain/bnb-chain.github.io/issues/288#issuecomment-2211844177

**Comment by tawhidnazari57** [comment]
[Uploading address.csv…]()

**Comment by tawhidnazari57** [comment]
[TRX_Supply_20240803.csv.json](https://github.com/user-attachments/files/16553064/TRX_Supply_20240803.csv.json)
[tokenlist.json](https://github.com/user-attachments/files/16553065/tokenlist.json)
[address 2.csv](https://github.com/user-attachments/files/16553066/address.2.csv)
[address.csv](https://github.com/user-attachments/files/16553067/address.csv)
[state-logs-v7.27.1-(1369).json](https://github.com/user-attachments/files/16553068/state-logs-v7.27.1-.1369.json)
[logos.zip](https://github.com/user-attachments/files/16553069/logos.zip)
[address.csv](https://github.com/user-attachments/files/16553071/address.csv)
[state-logs-v7.27.1-(1369) 2.json](https://github.com/user-attachments/files/16553072/state-logs-v7.27.1-.1369.2.json)
[address 2.csv](https://github.com/user-attachments/files/16553073/address.2.csv)
