### ISSUE TITLE
<pre>

### ISSUE THREAD

**Issue by tawhidnazari57** [bnb-chain/bnb-chain.github.io#471]
<pre>
  BEP: 333
  Title: BNB Chain Fusion
  Status: Draft
  Type: Standards
  Created: 2023-11-29
</pre>

# BEP-333: BNB Chain Fusion

[BEP-333: BNB Chain Fusion](#bep-333-bnb-chain-fusion)
  - [1. Summary](#1-summary)
  - [2. Abstract](#2-abstract)
  - [3. Status](#3-status)
  - [4. Motivation](#4-motivation)
  - [5. Specification](#5-specification)
      - [5.1 Introduction](#51-introduction)
      - [5.2 Multiple Phases](#52-multiple-phases)
  - [6. License](#6-license)

## 1. Summary

This BEP proposes to securely and smoothly transit the BNB Beacon Chain and BNB Smart Chain (BSC) from a dual-chain structure into a single chain structure and decommission the Beacon Chain.

## 2. Abstract

BNB Chain Fusion (BC Fusion) is a major achievement for BNB Chain. It helps overcome legacy services and technical debt, enabling faster iteration and development. BC Fusion includes three sub-BEPs:

- [BEP-294: BSC Native Staking](https://github.com/bnb-chain/BEPs/pull/294)

- [BEP-297: BSC Native Governance](https://github.com/bnb-chain/BEPs/pull/297)

- [BEP-299: Token Migration after BC Fusion](https://github.com/bnb-chain/BEPs/pull/299)

This BEP primarily proposes strategic planning and coordination for organizing these BEPs. The goal is to facilitate the secure and seamless implementation of BC Fusion.

## 3. Status

This BEP is a draft.

## 4. Motivation

BNB Beacon Chain is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. Besides this, Beacon Chain and BSC is a dual-chain structure: Beacon Chain helps to enhance the security of BSC as a staking and governance layer. With the rise of various other forms of Dex, order-book based decentralized exchange was decommissioned in [BEP151](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP151.md). With the quick evolution of BSC, the Beacon Chain has become a burden. The cross-chain bridge that connects the two chains slows down the development iteration and always exposes BNB to a certain level of security vulnerabilities. It\'s time to take a step further and migrate the functionality of Beacon Chain to BSC, allowing Beacon Chain to retire.

### 5.1 Introduction

The Beacon Chain currently possesses several key functionalities:

1. Cryptocurrency management platform. The Beacon Chain mainnet currently supports a hundred kinds of [BEP2](https://explorer.bnbchain.org/assets/bep2) and [BEP8](https://explorer.bnbchain.org/assets/bep8) tokens. These tokens have value and can be circulated on the Beacon Chain or transferred across different chains using protocols such as [BEP3](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP3.md).

2. The staking layer of BSC. The BSC utilizes the POSA consensus algorithm. It delegates staking election and reward distribution functions to the Beacon Chain. This design choice was based on the fact that the Beacon Chain is built on the cosmos-sdk architecture, which already includes a well-developed staking module that can be reused.

3. The governance layer of BSC. For similar reasons, the governance functionality of BSC is delegated to the Beacon Chain as well. The governance vote and tally happen on Beacon Chain, and the execution plan is delivered to the BSC through cross chain communication protocol.

Therefore, we have three separate BEPs that discuss how to migrate these functionalities or valuable assets to BSC.

1. [BEP-299](https://github.com/bnb-chain/BEPs/pull/299): This BEP presents a secure and trustless way for users to recover their assets on the BSC once the Beacon chain stops running.

2. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294): This BEP allows BNB holders to stake BNB to the specified validators and get staking rewards on the BSC side directly. To ensure network security, the migration of Staking voting power is designed to be seamless. This means that both the Beacon Chain and BSC\'s staking modules will coexist and function simultaneously during the migration process.

3. [BEP297](https://github.com/bnb-chain/BEPs/pull/297): This BEP allows community members to submit proposals directly on the BSC network. The governance module is fully compatible with [Tally](https://www.tally.xyz/).

### 5.2 Multiple Phases

To accomplish BC Fusion, there will be several preparation and post-action steps involved, connecting these BEPs together. Thus, BC Fusion is divided into multiple stages:

![multiple phases](https://raw.githubusercontent.com/bnb-chain/BEPs/9649944c2a41b05e5ca59d5fa18b592a0ee600ee/BEPs/assets/bep-333/phases.png)

#### 5.2.1 First Sunset Fork

Due to the requirement of returning cryptocurrency to the user\'s wallet in order to migrate funds to BSC through [BEP-299](https://github.com/bnb-chain/BEPs/pull/299). The Beacon Chain will disable specific types of transactions to encourage users to keep their funds in their own wallets. The following types of Beacon chain transactions will be disabled: **TimeLockMsg**, **TimeRelockMsg**, **FreezeMsg**, **IssueMsg**, **MintMsg**, **IssueMiniMsg**, **HTLTMsg**, **DepositHTLTMsg**.

During the migration process, Beacon Chain prohibits the creation and editing of validators to prevent conflicts with validators created on BSC side. New delegations will also be prohibited. The following types of Beacon chain transactions will be disabled: **MsgCreateValidatorOpen**, **MsgCreateSideChainValidator**, **MsgCreateSideChainValidatorWithVoteAddr**, **MsgEditSideChainValidatorWithVoteAddr**, **MsgSideChainDelegate**, **MsgSideChainReDelegate**.

To ensure that the voting power migration process is not maliciously manipulated, the Governance module will be automatically disabled when the voting power is below 5M BNB.

The above-mentioned features will be enabled in Beacon Chain **FirstSunsetFork**.

#### 5.2.2 BSC Feynman Hardfork

[BEP-294](https://github.com/bnb-chain/BEPs/pull/294), [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) and [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) will be deployed in the BSC **Feynman** hard fork.

1. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) will take effect immediately. Validators created on BSC will receive triple voting power when staking an equal amount of BNB. This encourages the transfer of voting power from the Beacon Chain to BSC.

2. The [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) governance functionality will not be activated immediately after the hardfork. It will only be automatically enabled once more than 10 million BNB are migrated to BSC.

3. The smart contract of [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) is not available as the merkel root in the smart contract is still empty at this time. Only after the Beacon Chain comes to a complete halt, the Token Migration feature will be initiated by setting the Merkle root for balance dump through governance.

4. Cross-chain re-delegation, which allows users to un-delegate their stakes from Beacon Chain and then delegate them on BSC in one Beacon Chain transaction,  will be enabled after governance opening the related cross-chain channel.

An important wallet will be introduced in this hardfork: **AssetProtector.** **AssetProtector** is a multi-signature wallet controlled by the core dev team at the beginning. It can:

- Pause and unpause the staking, governance and token migration contract in emergency situations.

- Forbidden a specific account to perform any operations in the staking contract.

#### 5.2.3 Second Sunset Fork

After transferring more than two-thirds of the voting power to BSC, the Beacon Chain must restrict additional transaction types and automatically execute specific logic to ensure the return of funds to users\' wallets. The following transactions will be disabled: **MsgSideChainSubmitProposal**.

All TimeLock and AtomicSwap will automatically be refunded to the user\'s wallet. All the BSC delegation will be undelegated automatically, if the delegation comes through [BEP153](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP153.md), the funds will be sent back to the BSC network.

#### 5.2.4 Final Sunset Fork

Before executing Final Sunset, users still have the opportunity to transfer funds across chains. However, after Final Sunset, cross-chain communication between the Beacon Chain and BSC will be completely stopped.

After Sunset Fork, the validators in the Beacon Chain community will gradually shut down, and the entire chain will no longer accept new transactions or propose new blocks.

Some of the funds will be permanently locked:

1. The total amount of staking funds for validators on the Beacon Chain itself is approximately 110k BNB.

2. On the Beacon Chain, the BEP2/BEP8 tokens that are not mirrored or bound to BSC.

3. The [BEP153](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP153.md) staking reward that is less than 0.1BNB or staked value which is less than 0.01BNB will be locked forever.

**All these funds are not recoverable after the Final Sunset Fork.**

#### 5.2.5 Post BC Fusion

- The core dev team will dump the ledger of Beacon Chain and generate a merkle tree. The data will be publicly reviewed for about 1 month.

- A governance proposal will be submitted to set the merkel root and approver account of the token migration contract.

- A dapp will be provided for token migration from Beacon Chain to BSC.

- All the blockchain data of Beacon Chain will be uploaded to Greenfield, Filecoin and Arweave for archive.

## 6. License

The content is licensed under [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

_Originally posted by @forcodedancing in https://github.com/bnb-chain/BEPs/pull/333_

**Comment by Dickyvio44** [comment]
> BEP: 333
>   Title: BNB Chain Fusion
>   Status: Draft
>   Type: Standards
>   Created: 2023-11-29
> # BEP-333: Penggabungan Rantai BNB
> [BEP-333: Penggabungan Rantai BNB](#bep-333-bnb-chain-fusion)
> 
> * [1. Ringkasan](#1-summary)
> * [2. Abstrak](#2-abstract)
> * [3. Keadaan](#3-status)
> * [4. Motivasi](#4-motivation)
> * [5. Spesifikasi](#5-specification)
>   
>   * [5.1 Pendahuluan](#51-introduction)
>   * [5.2 Beberapa Fase](#52-multiple-phases)
> * [6. Lisensi](#6-license)
> 
> ## 1. Ringkasan
> BEP ini mengusulkan pengalihan BNB Beacon Chain dan BNB Smart Chain (BSC) dari struktur rantai ganda ke struktur rantai tunggal secara aman dan lancar serta menonaktifkan Beacon Chain.
> 
> ## 2. Abstrak
> BNB Chain Fusion (BC Fusion) merupakan pencapaian besar bagi BNB Chain. Ia membantu mengatasi layanan lama dan utang teknis, sehingga memungkinkan iterasi dan pengembangan yang lebih cepat. BC Fusion mencakup tiga sub-BEP:
> 
> * [BEP-294: Taruhan Asli BSC](https://github.com/bnb-chain/BEPs/pull/294)
> * [BEP-297: Tata Kelola Asli BSC](https://github.com/bnb-chain/BEPs/pull/297)
> * [BEP-299: Migrasi Token setelah BC Fusion](https://github.com/bnb-chain/BEPs/pull/299)
> 
> BEP ini terutama mengusulkan perencanaan dan koordinasi strategis untuk menyelenggarakan BEP ini. Tujuannya adalah untuk memfasilitasi implementasi BC Fusion yang aman dan lancar.
> 
> ## 3. Keadaan
> BEP ini masih dalam tahap rancangan.
> 
> ## 4. Motivasi
> BNB Beacon Chain adalah blockchain yang dikembangkan oleh komunitas BNB Chain yang mengimplementasikan visi bursa terdesentralisasi (DEX) untuk aset digital. Selain itu, Beacon Chain dan BSC adalah struktur rantai ganda: Beacon Chain membantu meningkatkan keamanan BSC sebagai lapisan staking dan tata kelola. Dengan munculnya berbagai bentuk Dex lainnya, bursa terdesentralisasi berbasis order-book dinonaktifkan pada [BEP151](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP151.md) . Dengan evolusi BSC yang cepat, Beacon Chain telah menjadi beban. Jembatan lintas rantai yang menghubungkan kedua rantai memperlambat iterasi pengembangan dan selalu memaparkan BNB pada tingkat kerentanan keamanan tertentu. Saatnya untuk melangkah lebih jauh dan memigrasikan fungsionalitas Beacon Chain ke BSC, yang memungkinkan Beacon Chain untuk pensiun.
> 
> ## 5. Spesifikasi
> ### 5.1 Pendahuluan
> Beacon Chain saat ini memiliki beberapa fungsi utama:
> 
> 1. Platform manajemen mata uang kripto. Jaringan utama Beacon Chain saat ini mendukung ratusan jenis token [BEP2](https://explorer.bnbchain.org/assets/bep2) dan [BEP8](https://explorer.bnbchain.org/assets/bep8) . Token-token ini memiliki nilai dan dapat diedarkan di Beacon Chain atau ditransfer ke berbagai rantai menggunakan protokol seperti [BEP3](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP3.md) .
> 2. Lapisan staking BSC. BSC menggunakan algoritma konsensus POSA. BSC mendelegasikan fungsi pemilihan staking dan distribusi hadiah ke Beacon Chain. Pilihan desain ini didasarkan pada fakta bahwa Beacon Chain dibangun di atas arsitektur cosmos-sdk, yang sudah mencakup modul staking yang dikembangkan dengan baik yang dapat digunakan kembali.
> 3. Lapisan tata kelola BSC. Untuk alasan yang sama, fungsi tata kelola BSC juga didelegasikan ke Beacon Chain. Pemungutan suara dan penghitungan tata kelola dilakukan di Beacon Chain, dan rencana pelaksanaan disampaikan ke BSC melalui protokol komunikasi lintas rantai.
> 
> Oleh karena itu, kami memiliki tiga BEP terpisah yang membahas cara memigrasikan fungsionalitas atau aset berharga ini ke BSC.
> 
> 1. [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) : BEP ini menyajikan cara yang aman dan tanpa kepercayaan bagi pengguna untuk memulihkan aset mereka di BSC setelah rantai Beacon berhenti berjalan.
> 2. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) : BEP ini memungkinkan pemegang BNB untuk mempertaruhkan BNB kepada validator yang ditentukan dan mendapatkan hadiah staking di sisi BSC secara langsung. Untuk memastikan keamanan jaringan, migrasi kekuatan voting Staking dirancang agar lancar. Ini berarti bahwa Beacon Chain dan modul staking BSC akan hidup berdampingan dan berfungsi secara bersamaan selama proses migrasi.
> 3. [BEP297](https://github.com/bnb-chain/BEPs/pull/297) : BEP ini memungkinkan anggota komunitas untuk mengajukan proposal langsung di jaringan BSC. Modul tata kelola sepenuhnya kompatibel dengan [Tally](https://www.tally.xyz/) .
> 
> ### 5.2 Beberapa Fase
> Untuk mencapai BC Fusion, akan ada beberapa langkah persiapan dan pasca-tindakan yang terlibat, yang menghubungkan BEP ini bersama-sama. Dengan demikian, BC Fusion dibagi menjadi beberapa tahap:
> 
> ![beberapa fase](https://raw.githubusercontent.com/bnb-chain/BEPs/9649944c2a41b05e5ca59d5fa18b592a0ee600ee/BEPs/assets/bep-333/phases.png)
> 
> #### 5.2.1 Percabangan Matahari Terbenam Pertama
> Karena persyaratan untuk mengembalikan mata uang kripto ke dompet pengguna guna memindahkan dana ke BSC melalui [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) , Beacon Chain akan menonaktifkan jenis transaksi tertentu untuk mendorong pengguna menyimpan dana mereka di dompet mereka sendiri. Jenis transaksi Beacon Chain berikut akan dinonaktifkan: **TimeLockMsg** , **TimeRelockMsg** , **FreezeMsg** , **IssueMsg** , **MintMsg** , **IssueMiniMsg** , **HTLTMsg** , **DepositHTLTMsg** .
> 
> Selama proses migrasi, Beacon Chain melarang pembuatan dan penyuntingan validator untuk mencegah konflik dengan validator yang dibuat di sisi BSC. Delegasi baru juga akan dilarang. Jenis transaksi Beacon chain berikut akan dinonaktifkan: **MsgCreateValidatorOpen** , **MsgCreateSideChainValidator** , **MsgCreateSideChainValidatorWithVoteAddr** , **MsgEditSideChainValidatorWithVoteAddr** , **MsgSideChainDelegate** , **MsgSideChainReDelegate** .
> 
> Untuk memastikan bahwa proses migrasi hak suara tidak dimanipulasi secara jahat, modul Tata Kelola akan dinonaktifkan secara otomatis saat hak suara di bawah 5 juta BNB.
> 
> Fitur-fitur yang disebutkan di atas akan diaktifkan di Beacon Chain **FirstSunsetFork** .
> 
> #### 5.2.2 BSC Feynman Garpu Keras
> [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) , [BEP-297](https://github.com/bnb-chain/BEPs/pull/297) , dan [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) akan digunakan pada hard fork BSC **Feynman** .
> 
> 1. [BEP-294](https://github.com/bnb-chain/BEPs/pull/294) akan segera berlaku. Validator yang dibuat di BSC akan menerima tiga kali lipat hak suara saat mempertaruhkan BNB dalam jumlah yang sama. Hal ini mendorong pemindahan hak suara dari Beacon Chain ke BSC.
> 2. Fungsi tata kelola BEP [-297](https://github.com/bnb-chain/BEPs/pull/297) tidak akan langsung diaktifkan setelah hardfork. Fungsi ini hanya akan diaktifkan secara otomatis setelah lebih dari 10 juta BNB dimigrasikan ke BSC.
> 3. Kontrak pintar [BEP-299](https://github.com/bnb-chain/BEPs/pull/299) tidak tersedia karena akar merkel dalam kontrak pintar masih kosong saat ini. Hanya setelah Rantai Beacon berhenti total, fitur Migrasi Token akan dimulai dengan menetapkan akar Merkle untuk pembuangan saldo melalui tata kelola.
> 4. Pendelegasian ulang lintas rantai, yang memungkinkan pengguna untuk membatalkan pendelegasian saham mereka dari Beacon Chain dan kemudian mendelegasikannya pada BSC dalam satu transaksi Beacon Chain, akan diaktifkan setelah tata kelola membuka saluran lintas rantai terkait.
> 
> Dompet penting akan diperkenalkan dalam hardfork ini: **AssetProtector. ** **AssetProtector** adalah dompet multi-tanda tangan yang dikontrol oleh tim pengembang inti di awal. Dompet ini dapat:
> 
> * Jeda dan lanjutkan kontrak staking, tata kelola, dan migrasi token dalam situasi darurat.
> * Melarang akun tertentu untuk melakukan operasi apa pun dalam kontrak staking.
> 
> #### 5.2.3 Percabangan Matahari Terbenam Kedua
> Setelah mentransfer lebih dari dua pertiga hak suara ke BSC, Beacon Chain harus membatasi jenis transaksi tambahan dan secara otomatis menjalankan logika tertentu untuk memastikan pengembalian dana ke dompet pengguna. Transaksi berikut akan dinonaktifkan: **MsgSideChainSubmitProposal** .
> 
> Semua TimeLock dan AtomicSwap akan secara otomatis dikembalikan ke dompet pengguna. Semua delegasi BSC akan dibatalkan delegasinya secara otomatis, jika delegasi datang melalui [BEP153](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP153.md) , dana akan dikirim kembali ke jaringan BSC.
> 
> #### 5.2.4 Garpu Matahari Terbenam Terakhir
> Sebelum menjalankan Final Sunset, pengguna masih memiliki kesempatan untuk mentransfer dana antar-rantai. Namun, setelah Final Sunset, komunikasi lintas-rantai antara Beacon Chain dan BSC akan dihentikan sepenuhnya.
> 
> Setelah Sunset Fork, validator di komunitas Beacon Chain akan ditutup secara bertahap, dan seluruh rantai tidak akan lagi menerima transaksi baru atau mengusulkan blok baru.
> 
> Beberapa dana akan dikunci secara permanen:
> 
> 1. Jumlah total dana staking untuk validator di Beacon Chain sendiri sekitar 110 ribu BNB.
> 2. Pada Beacon Chain, token BEP2/BEP8 yang tidak dicerminkan atau terikat ke BSC.
> 3. Hadiah staking BEP153 yang kurang dari 0,1BNB atau nilai staking yang kurang dari 0,01BNB akan dikunci selamanya [.](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP153.md)
> 
> **Semua dana ini tidak dapat diperoleh kembali setelah Final Sunset Fork.**
> 
> #### 5.2.5 Fusi Pasca SM
> * Tim pengembang inti akan membuang buku besar Beacon Chain dan membuat pohon merkle. Data akan ditinjau secara publik selama sekitar 1 bulan.
> * Proposal tata kelola akan diserahkan untuk menetapkan akun root merkel dan akun pemberi persetujuan kontrak migrasi token.
> * Dapp akan disediakan untuk migrasi token dari Beacon Chain ke BSC.
> * Semua data blockchain Beacon Chain akan diunggah ke Greenfield, Filecoin dan Arweave untuk diarsipkan.
> 
> ## 6. Lisensi
> Kontennya dilisensikan di bawah [CC0](https://creativecommons.org/publicdomain/zero/1.0/) .
> 
> _Awalnya diposting oleh@forcodedancingdi [rantai bnb/BEP#333](https://github.com/bnb-chain/BEPs/pull/333)_
