### ISSUE TITLE
> 0xaceCe846E9C3448DD465E9219C56A77ba5ac6000

### ISSUE THREAD

**Issue by Kya123iu** [bnb-chain/bnb-chain.github.io#483]
> 0xaceCe846E9C3448DD465E9219C56A77ba5ac6000
> 
> _Originally posted by @Ali3219 in https://github.com/bnb-chain/BEPs/pull/441#discussion_r1783352435_

_Originally posted by @Kya123iu in https://github.com/bnb-chain/bsc/issues/2730#issuecomment-2409293679_

**Comment by YungBS** [comment]
> > 0xaceCe846E9C3448DD465E9219C56A77ba5ac6000
> > 
> > _Originally posted by @Ali3219 in https://github.com/bnb-chain/BEPs/pull/441#discussion_r1783352435_
> 
> 
> 
> _Originally posted by @Kya123iu in https://github.com/bnb-chain/bsc/issues/2730#issuecomment-2409293679_
