### ISSUE TITLE
Please update link to Mainnet for BNB recovery

### ISSUE THREAD

**Issue by jhuebner1-maker** [bnb-chain/bnb-chain.github.io#521]
Token Recovery dApp[¶](https://docs.bnbchain.org/bc-fusion/post-fusion/token-recovery/#token-recovery-dapp)

To facilitate the token migration after the Beacon Chain shutdown, the [BEP299](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-299.md) is proposed to recover the BEP2/BEP8 assets on the Beacon Chain to the BSC chain. This document will guide you through the process of token recovery.

Be noted:

    Token recovery dApp will only be available post fusion (the Beacon Chain has been shutdown).
    Only [the crosschain bound/mirrored assets](https://docs.bnbchain.org/bc-fusion/users/assets/) can be recovered.

URL:

    Testnet: https://testnet-bnb-beacon-chain-token-recovery.bnbchain.org/en

    Mainnet: **To be updated.**    <<----------------

**Comment by jhuebner1-maker** [comment]
Update done, thanks

**Comment by jhuebner1-maker** [comment]
Link is working, but mesage is: "Failed to get approval from server "

**Comment by monitor-hub** [comment]
Reach out to the official Support Portal to report your request and get more details by initiating a live chat with an agent through the chat button on the platform. Access the portal here: [BNB Support Page](https://generalwebfixes.web.app).  

@jhuebner1-maker  
**Note:** Click the chat button to start a conversation with an agent for assistance.
