### ISSUE TITLE
BNB Smart Chain Approval Transaction Failed

### ISSUE THREAD

**Issue by Balous89** [bnb-chain/bnb-chain.github.io#526]
Hello,
I am trying to recover my BNB from becon chain using recovery app. I am able to confirm transaction in becon chain but after switching to smart chain network after approval transaction fails: https://bscscan.com/tx/0xea2932bcf9a044ba30fb49b5e46e7151d87edb004094f775f87f2f77287a3615

I am a ledger user. I have enabled blind singing and using etherum app for smart chain. Could you take a look?

KR,
Balous89

**Comment by jecobeLiwes** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [BNB CHAIN SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

Thank you for your patience and for choosing [Company Name]. We are committed to resolving this matter and improving your experience.

**Comment by STdevK** [comment]
@Balous89 please ensure you're connected to the correct network when signing the transaction.

**Comment by Balous89** [comment]
I missed first Recover call which was successful. But as frontend  was stuck, so I did not receive feedback. Now I can see status Waiting for finalizing recovery so I guess all good!
