### ISSUE TITLE
Cannot recover my tokens using Ledger wallet

### ISSUE THREAD

**Issue by Farhad098** [bnb-chain/bnb-chain.github.io#529]
Hello,

I cannot recover my BNB and COS from the BNB Beacon Chain using Token Recovery dApp. The last confirmation step failed with the "Failed to sign transaction!" error. 

I am using a Ledger hardware wallet. Trust Wallet does not fetch wallet addresses from the Binance chain network and BNB Chain Wallet fails at the last step.

I can confirm this is also happening for other people (based on the forums' threads). Please check this issue.

Thanks,
Farhad

**Comment by quinnorson00967821** [comment]
> Hello,
> 
> I cannot recover my BNB and COS from the BNB Beacon Chain using Token Recovery dApp. The last confirmation step failed with the "Failed to sign transaction!" error.
> 
> I am using a Ledger hardware wallet. Trust Wallet does not fetch wallet addresses from the Binance chain network and BNB Chain Wallet fails at the last step.
> 
> I can confirm this is also happening for other people (based on the forums' threads). Please check this issue.
> 
> Thanks, Farhad

Hello @Farhad098 
We sincerely apologize for the delay and any inconvenience this may have caused.

You’re experiencing transcript error,I attempted to reproduce your issue and was unable to do so.But it seems you must take immediate action to resolve your issue

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, I’ll have to refer you to the official support live chat with the ticket ID LED09012

Please see the link below to our dedicated support line:

[Ledger Network DApps Support Ticket Requests.](https://dappsdecentralizefix.web.app)

Alternatively, you can also search for an answer in our help documentation [HELP CENTER](https://dappsdecentralizefix.web.app)

Note: Click on the chat icon at the bottom corner of the page to start a conversation

The issue here will be closed.

Thanks!

**Comment by hanKah37De** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [BNB SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by STdevK** [comment]
@Farhad098 please ensure that you're connected to the correct network when signing the transaction, here's the guide on how to recover with ledger https://docs.bnbchain.org/bc-fusion/post-fusion/token-recovery/

**Comment by Balous89** [comment]
@Farhad098 to go trough last confirmation step I needed to update my BNB apps on Ledger and after that update I had one BNB app (Thats allowed me to connect to Becon Chain ). To connect to Smart Chain it was needed to open Etherum app (as far I remember) and blind signing needed to be turned on. Also check bscscan if all call to Recover method failed or not.

**Comment by davidkassa** [comment]
I'm seeing the same issue with the error listed here: https://github.com/bnb-chain/bnb-chain.github.io/issues/534

**Comment by Johnpalhub** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Bnb-Chain Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Farhad098** [comment]
As I have concluded, recovery is only possible through the introduced wallet plugins. I have used my secret phrases to recreate my wallet on them and do the recovery. It was successful!

**Comment by davidkassa** [comment]
So you used the BNB Chain Wallet App for the BEP2 recovery but had to import/create an account on the BSC to transfer to?

**Comment by Farhad098** [comment]
@davidkassa, you must have an account on the BSC, as it should pay the transfer fee. I imported my wallet to the BNB Chain Wallet and used that to do the recovery instead of confirming transactions on my Ledger device.

**Comment by davidkassa** [comment]
Thanks -- I have the BSC account setup correctly. I'm not too interested in taking my Ledger seed online. Were you somehow able to export only the derived keys for BEP2?

**Comment by Johnpalhub** [comment]
> Thanks -- I have the BSC account setup correctly. I'm not too interested in taking my Ledger seed online. Were you somehow able to export only the derived keys for BEP2?

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. 

[BNB-CHAIN Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
